project:
  type: book
  output-dir: _book
  
# Book formatting types and options
format:
  html:
    theme: 
      - cosmo
  pdf:
    documentclass: scrreprt
      
# Bibliography and citation options
bibliography: references.bib
csl: ama.csl

# Set editor to default to source view instead of visual view
editor: source

# To make sure that R, Python, and Julia code is only executed locally, 
# configure your project to use Quarto’s freeze feature by adding this to your 
# _quarto.yml. (https://quarto.org/docs/publishing/netlify.html)
execute:
  freeze: auto

# Book structure and options
book:
  title: "Shiny Notes"
  author: "Brad Cannell"
  date: today
  repo-url: https://github.com/brad-cannell/shiny_notes_quarto
  repo-actions: [edit]
  page-footer: 
    left: |
      Shiny Notes
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  search: true
  chapters:
  # Index is the landing page for the HTML version of the book.
    - index.qmd



